seeding:
  dummies:
    artists:
      min: 1
      max: 1
    tracks:
      min: 0
      max: 10
    tabs:
      min: 0
      max: 4
  instruments:
    - id: 1
      name: 'Electric Guitar'
    - id: 2
      name: 'Acoustic Guitar'
    - id: 3
      name: 'Bass Guitar'
    - id: 4
      name: 'Drums'
  difficulties:
    - id: 1
      name: 'Easy'
    - id: 2
      name: 'Intermediate'
    - id: 3
      name: 'Hard'
    - id: 4
      name: 'Expert'
  sources:
    - id: 1000
      name: 'Music Provider 1'
      categories: ['artists', 'tracks']
    - id: 2000
      name: 'Tab Provider 1'
      categories: ['tabs']
  endpoints:
    - sourceId: 1000
      category: 'artist'
      type: 'web'
      url: 'https://musicprovider1/artist/$s'
    - sourceId: 1000
      category: 'track'
      type: 'web'
      url: 'https://musicprovider1/track/$s'
    - sourceId: 2000
      category: 'artist'
      type: 'web'
      url: 'https://tabprovider1/artist/$s'
    - sourceId: 2000
      category: 'tab'
      type: 'api'
      url: 'https://tabprovider1/artist/api/$s'