seeding:
  dummies:
    artists:
      min: 1
      max: 1
      tracks:
        min: 1
        max: 1
        tabs:
          min: 1
          max: 1
  instruments:
    - id: 1
      name: 'electric guitar'
    - id: 2
      name: 'acoustic guitar'
    - id: 3
      name: 'bass guitar'
    - id: 4
      name: 'drums'
  difficulties:
    - id: 1
      name: 'easy'
    - id: 2
      name: 'intermediate'
    - id: 3
      name: 'hard'
    - id: 4
      name: 'expert'
  sources:
    - id: 1000
      name: 'Music Provider 1'
      category: 'music'
    - id: 2000
      name: 'Tab Provider 1'
      category: 'tabs'
  endpoints:
    - sourceId: 1000
      category: 'artist'
      type: 'web'
      url: 'https://musicprovider1/artist/{artistID}'
    - sourceId: 1000
      category: 'track'
      type: 'web'
      url: 'https://musicprovider1/track/{trackID}'
    - sourceId: 2000
      category: 'artist'
      type: 'web'
      url: 'https://tabprovider1/artist/{artistID}'
    - sourceId: 2000
      category: 'tab'
      type: 'web'
      url: 'https://tabprovider1/track/{trackID}'
    - sourceId: 2000
      category: 'artist'
      type: 'api'
      url: 'https://tabprovider1/artist/api/{artistID}'