dummies:
  artists:
    min: 1
    max: 1
  tracks:
    min: 0
    max: 10
  tabs:
    min: 0
    max: 4
seeds:
  sources:
    - source:
        id: 1
        name: 'Music Provider 1'
    - source:
        id: 2
        name: 'Tab Provider 1'
  endpoints:
    - endpoint:
      sourceId: 1
      category: 'Artist'
      url: 'https://musicprovider1/artist/$s'
    - endpoint:
      sourceId: 1
      category: 'Track'
      url: 'https://musicprovider1/track/$s'
    - endpoint:
      sourceId: 2
      category: 'Tab'
      url: 'https://tabprovider1/tab/$s'