dummies:
  artists:
    min: 1
    max: 1
  tracks:
    min: 0
    max: 10
  tabs:
    min: 0
    max: 4
seeds:
  instruments:
    - id: 1
      name: 'Electric Guitar'
    - id: 2
      name: 'Acoustic Guitar'
    - id: 3
      name: 'Bass Guitar'
    - id: 4
      name: 'Drums'
  difficulties:
    - id: 1
      name: 'Easy'
    - id: 2
      name: 'Intermediate'
    - id: 3
      name: 'Hard'
    - id: 4
      name: 'Expert'
  sources:
    - id: 1
      name: 'Music Provider 1'
    - id: 2
      name: 'Tab Provider 1'
  endpoints:
    - sourceId: 1
      category: 'Artist'
      url: 'https://musicprovider1/artist/$s'
    - sourceId: 1
      category: 'Track'
      url: 'https://musicprovider1/track/$s'
    - sourceId: 2
      category: 'Tab'
      url: 'https://tabprovider1/tab/$s'